name: CI
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala_version: [2.13.2, 2.12.11]
        platform: [jvm, js]
    env:
      PLATFORM: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Coursier cache
      uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: zulu:8.0.432
        apps: sbt scala

    - name: JS Tests
      if: ${{ matrix.platform != 'js' }}
      run: sbt "++${{ matrix.scala_version }}" testsJS/test propsJS/test

    - name: JVM Tests
      if: ${{ matrix.platform != 'jvm' }}
      run: sbt "++${{ matrix.scala_version }}" testsJVM/test propsJVM/test

    - name: Clean up
      run: |
        rm -rf "$HOME/.ivy2/local" || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true
